// ===============================================================
// AI SMART RAILWAY MANAGEMENT SYSTEM - CORE TYPES
// Developer: MOHITH S | smohith002@gmail.com
// ===============================================================

export type RailwayRole =
  | 'super_admin'
  | 'railway_admin'
  | 'zonal_admin'
  | 'divisional_manager'
  | 'station_master'
  | 'assistant_station_master'
  | 'train_controller'
  | 'loco_pilot'
  | 'assistant_loco_pilot'
  | 'train_manager_guard'
  | 'tte'
  | 'te'
  | 'rpf_security'
  | 'maintenance_staff'
  | 'electrical_staff'
  | 'signal_telecom_staff'
  | 'track_maintenance_staff'
  | 'coach_maintenance_staff'
  | 'control_room_operator'
  | 'medical_emergency_staff'
  | 'hr_staff_admin'
  | 'authorized_contractor'
  | 'passenger';

export interface RoleDefinition {
  id: RailwayRole;
  title: string;
  category: 'Administration' | 'Operations' | 'Running Crew' | 'Ticketing & Security' | 'Engineering & Maintenance' | 'Emergency & HR' | 'Public';
  description: string;
  jurisdictionLevel: 'National' | 'Zone' | 'Division' | 'Station' | 'Train' | 'Unit' | 'Public';
  permissions: string[];
}

export type TrainStatus =
  | 'ON_TIME'
  | 'DELAYED'
  | 'SEVERELY_DELAYED'
  | 'CANCELLED'
  | 'DIVERTED'
  | 'TERMINATED'
  | 'UNKNOWN'
  | 'STALE'
  | 'DATA_UNAVAILABLE';

export type FreshnessState =
  | 'LIVE'             // 0-30s
  | 'RECENT'           // 30s-5m
  | 'STALE'            // 5m+
  | 'LAST_KNOWN'       // Disconnected after previous valid fix
  | 'DATA_UNAVAILABLE'; // Zero data received

export interface TrainPosition {
  id: string;
  trainId: string;
  trainNumber: string;
  trainName: string;
  latitude: number;
  longitude: number;
  speedKmph: number;
  headingDegrees: number;
  status: TrainStatus;
  telemetryType?: 'EXACT_GPS' | 'STATION_REPORTED' | 'INTER_STATION_ESTIMATE' | 'OFFLINE_SCHEDULE';
  nextStationCode: string;
  nextStationName: string;
  previousStationCode: string;
  previousStationName: string;
  lastReportedStationCode?: string;
  lastReportedStationName?: string;
  lastReportedTime?: string;
  locationMessage?: string;
  delayMinutes: number;
  source: string;
  receivedAt: string;        // ISO timestamp when server received data
  providerTimestamp: string; // ISO timestamp generated by telemetry device
  dataQuality: 'EXCELLENT' | 'DEGRADED' | 'UNVERIFIED' | 'SIMULATED';
  freshnessState: FreshnessState;
  distanceCoveredKm: number;
  totalDistanceKm: number;
  platformNumber?: string;
  nextStationScheduledArrival?: string;
  currentTrackSection?: string;
  signalAspect?: 'GREEN' | 'DOUBLE_YELLOW' | 'YELLOW' | 'RED';
}

export interface StationScheduleItem {
  stationCode: string;
  stationName: string;
  scheduledArrival: string;
  scheduledDeparture: string;
  actualArrival?: string;
  actualDeparture?: string;
  estimatedArrival?: string;
  estimatedDeparture?: string;
  platform: string;
  distanceKm: number;
  haltMinutes: number;
  status: 'PASSED' | 'CURRENT' | 'UPCOMING';
  dayCount: number;
  delayMinutes?: number;
}

export interface TrainDetails {
  id: string;
  trainNumber: string;
  trainName: string;
  trainType: 'VANDE_BHARAT' | 'RAJDHANI' | 'SHATABDI' | 'TEJAS' | 'DURONTO' | 'SUPERFAST' | 'EXPRESS' | 'FREIGHT';
  originStationCode: string;
  originStationName: string;
  destinationStationCode: string;
  destinationStationName: string;
  zone: string;
  division: string;
  rakeType: string;
  locoNumber: string;
  totalCoaches: number;
  schedule: StationScheduleItem[];
  currentPosition?: TrainPosition;
  assignedCrew?: {
    locoPilot?: StaffMember;
    assistantLocoPilot?: StaffMember;
    trainManager?: StaffMember;
    tteList?: StaffMember[];
  };
}

export interface RailwayStation {
  id: string;
  code: string;
  name: string;
  zone: string;
  division: string;
  latitude: number;
  longitude: number;
  category: 'TERMINAL' | 'MAJOR_JUNCTION' | 'JUNCTION' | 'STATION' | 'HALT';
  platformsCount: number;
  platforms: {
    number: number;
    occupyingTrain?: string;
    status: 'CLEAR' | 'OCCUPIED' | 'MAINTENANCE';
    signalAspect: 'GREEN' | 'DOUBLE_YELLOW' | 'YELLOW' | 'RED';
  }[];
}

export type AttendanceStatus =
  | 'PRESENT'
  | 'ABSENT'
  | 'ON_DUTY'
  | 'OFF_DUTY'
  | 'LEAVE'
  | 'TRAINING'
  | 'SICK_LEAVE'
  | 'EMERGENCY';

export interface StaffMember {
  id: string;
  employeeId: string;
  name: string;
  email: string;
  phone: string;
  role: RailwayRole;
  designation: string;
  zone: string;
  division: string;
  stationCode: string;
  department: 'Operations' | 'Mechanical' | 'Electrical' | 'Signal & Telecom' | 'Engineering' | 'Commercial' | 'Security' | 'Medical' | 'Personnel';
  medicalFitnessCategory: 'A-1' | 'A-2' | 'A-3' | 'B-1' | 'B-2' | 'C-1' | 'C-2';
  qualifications: string[];
  lastRestCompletedAt: string; // ISO Timestamp
  continuousDutyHours: number;
  attendanceStatus: AttendanceStatus;
  currentDutyId?: string;
  avatarUrl?: string;
}

export interface AttendanceRecord {
  id: string;
  staffId: string;
  staffName: string;
  employeeId: string;
  role: RailwayRole;
  date: string; // YYYY-MM-DD
  status: AttendanceStatus;
  signInTime?: string;
  signOutTime?: string;
  dutyStartTime?: string;
  dutyEndTime?: string;
  stationCode: string;
  geofenceVerified: boolean;
  remarks?: string;
  isCorrected?: boolean;
  correctedBy?: string;
  correctedAt?: string;
  createdAt: string;
}

export type DutyType =
  | 'RUNNING_TRAIN'
  | 'STATION_OPERATION'
  | 'YARD_PILOTING'
  | 'TRACK_MAINTENANCE'
  | 'SIGNAL_INSPECTION'
  | 'OHE_POWER_MAINTENANCE'
  | 'COACH_EXAMINATION'
  | 'SECURITY_ESCORT'
  | 'CONTROL_ROOM'
  | 'STANDBY_RELIEF';

export interface DutyAssignment {
  id: string;
  staffId: string;
  staffName: string;
  employeeId: string;
  role: RailwayRole;
  dutyType: DutyType;
  trainNumber?: string;
  stationCode?: string;
  sectionCode?: string;
  startTime: string; // ISO Timestamp
  endTime: string;   // ISO Timestamp
  reportingLocation: string;
  status: 'SCHEDULED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED' | 'REPLACED';
  assignedBy: string;
  assignedAt: string;
  instructions?: string;
}

export interface DutyChangeLog {
  id: string;
  dutyId: string;
  trainNumber?: string;
  role: RailwayRole;
  originalStaffId: string;
  originalStaffName: string;
  replacementStaffId: string;
  replacementStaffName: string;
  reason: string;
  changedBy: string;
  changedAt: string;
  approvalStatus: 'APPROVED' | 'PENDING' | 'EMERGENCY_OVERRIDE';
}

export interface CrewConflictResult {
  hasConflict: boolean;
  conflicts: {
    type: 'OVERLAPPING_DUTY' | 'INSUFFICIENT_REST' | 'QUALIFICATION_MISMATCH' | 'JURISDICTION_MISMATCH' | 'SICK_OR_LEAVE';
    severity: 'HIGH' | 'CRITICAL' | 'WARNING';
    description: string;
    details: string;
  }[];
}

export type IncidentCategory =
  | 'ACCIDENT'
  | 'MEDICAL'
  | 'FIRE'
  | 'TRACK_OBSTRUCTION'
  | 'SIGNAL_FAILURE'
  | 'EQUIPMENT_FAILURE'
  | 'SECURITY_ISSUE'
  | 'NATURAL_DISASTER'
  | 'OPERATIONAL_EMERGENCY'
  | 'OTHER';

export type IncidentSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export type IncidentStatus = 'REPORTED' | 'ACKNOWLEDGED' | 'ASSIGNED' | 'RESPONDING' | 'RESOLVED';

export interface IncidentRecord {
  id: string;
  incidentNumber: string;
  category: IncidentCategory;
  severity: IncidentSeverity;
  status: IncidentStatus;
  trainNumber?: string;
  stationCode?: string;
  section?: string;
  description: string;
  reportedBy: string;
  reportedAt: string;
  assignedTeam?: string;
  acknowledgedAt?: string;
  resolvedAt?: string;
  actionTaken?: string;
  auditTrail: {
    status: IncidentStatus;
    timestamp: string;
    updatedBy: string;
    note: string;
  }[];
}

export interface OperationalAlert {
  id: string;
  title: string;
  message: string;
  severity: 'INFO' | 'WARNING' | 'DANGER' | 'CRITICAL';
  targetAudience: RailwayRole[] | 'ALL';
  zone?: string;
  division?: string;
  trainNumber?: string;
  stationCode?: string;
  active: boolean;
  publishedBy: string;
  publishedAt: string;
  expiresAt?: string;
}

export interface DataSourceHealth {
  id: string;
  name: string;
  providerType: 'OFFICIAL' | 'AUTHORIZED' | 'GTFS_RT' | 'THIRD_PARTY' | 'SIMULATION';
  status: 'CONNECTED' | 'DEGRADED' | 'STALE' | 'OFFLINE' | 'ERROR' | 'NOT_CONFIGURED';
  lastSuccessfulSync: string;
  latencyMs: number;
  recordsReceivedLastHour: number;
  errorRatePercentage: number;
  circuitBreakerOpen: boolean;
  notes: string;
}

export interface AuditLogItem {
  id: string;
  userId: string;
  userName: string;
  userRole: RailwayRole;
  action: string;
  resource: string;
  resourceId?: string;
  previousState?: any;
  newState?: any;
  ipAddress?: string;
  timestamp: string;
}

export interface CopilotMessage {
  id: string;
  sender: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  citations?: {
    trainNumber?: string;
    stationCode?: string;
    staffId?: string;
    incidentId?: string;
    dataSource?: string;
    timestamp?: string;
  }[];
  suggestedActions?: string[];
  isVerifiedRealData: boolean;
}
